version: '3'

services:
    pyfhel:
        build: "https://github.com/albertopimpo/pyfhel-for-exam.git"
        image: pyfhel

    client:
        build: ./client
        depends_on:
            - pyfhel
        ports:
            - "8888:8888"
        networks:
            - security_network 
        tty: true
        stdin_open: true

    
    influxdb:
        image: influxdb
        environment:
            - INFLUXDB_DB=security_db
            - INFLUXDB_HTTP_AUTH_ENABLED=true
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=temp
        networks:
            - security_network
        
networks:
    security_network:
