version: '3'

services:
    pyfhel:
        build: https://github.com/ibarrond/Pyfhel.git
        entrypoint: bash
        networks:
            - security_network 
        tty: true
        stdin_open: true

    
    influxdb:
        image: influxdb
        environment:
            - INFLUXDB_DB=security_db
            - INFLUXDB_HTTP_AUTH_ENABLED=true
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=temp
        ports:
            - "8086:8086"
        networks:
            - security_network
        
networks:
    security_network:
